/**
 * App Router
 * BDEV: BDEV00000016
 *
 * PROTOTYPE - Non-functional application
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { bcttTheme } from '@bctt/design-system';

import { IncioCrditoHabitao } from './screens/IncioCrditoHabitao';
import { DadosdoImvel } from './screens/DadosdoImvel';
import { CondiesdeFinanciamento } from './screens/CondiesdeFinanciamento';
import { DadosPessoais } from './screens/DadosPessoais';
import { SituaoProfissional } from './screens/SituaoProfissional';
import { ResultadodaSimulao } from './screens/ResultadodaSimulao';
import { ConfirmaodePedido } from './screens/ConfirmaodePedido';

const App: React.FC = () => {
  return (
    <ThemeProvider theme={bcttTheme}>
      <CssBaseline />
      <BrowserRouter>
        <Routes>
        <Route path="/scr-001" element={<IncioCrditoHabitao />} />
        <Route path="/scr-002" element={<DadosdoImvel />} />
        <Route path="/scr-003" element={<CondiesdeFinanciamento />} />
        <Route path="/scr-004" element={<DadosPessoais />} />
        <Route path="/scr-005" element={<SituaoProfissional />} />
        <Route path="/scr-006" element={<ResultadodaSimulao />} />
        <Route path="/scr-007" element={<ConfirmaodePedido />} />
          <Route path="*" element={<Navigate to="/scr-001" replace />} />
        </Routes>
      </BrowserRouter>
    </ThemeProvider>
  );
};

export default App;
