/**
 * App Router
 * BDEV: BDEV00000011
 *
 * PROTOTYPE - Non-functional application
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { bcttTheme } from '@bctt/design-system';

import { SeleodeConta } from './screens/SeleodeConta';
import { ConsultadeSaldos } from './screens/ConsultadeSaldos';
import { ListadeMovimentos } from './screens/ListadeMovimentos';
import { DetalhedeMovimento } from './screens/DetalhedeMovimento';
import { SeleoFormatoExportao } from './screens/SeleoFormatoExportao';
import { ConfirmaoExportao } from './screens/ConfirmaoExportao';
import { FiltrosdeMovimentos } from './screens/FiltrosdeMovimentos';
import { MovimentosFiltrados } from './screens/MovimentosFiltrados';
import { SemResultados } from './screens/SemResultados';

const App: React.FC = () => {
  return (
    <ThemeProvider theme={bcttTheme}>
      <CssBaseline />
      <BrowserRouter>
        <Routes>
        <Route path="/scr-001" element={<SeleodeConta />} />
        <Route path="/scr-002" element={<ConsultadeSaldos />} />
        <Route path="/scr-003" element={<ListadeMovimentos />} />
        <Route path="/scr-004" element={<DetalhedeMovimento />} />
        <Route path="/scr-005" element={<SeleoFormatoExportao />} />
        <Route path="/scr-006" element={<ConfirmaoExportao />} />
        <Route path="/scr-007" element={<FiltrosdeMovimentos />} />
        <Route path="/scr-008" element={<MovimentosFiltrados />} />
        <Route path="/scr-009" element={<SemResultados />} />
          <Route path="*" element={<Navigate to="/scr-001" replace />} />
        </Routes>
      </BrowserRouter>
    </ThemeProvider>
  );
};

export default App;
