/**
 * Associar Conta Externa
 * Screen ID: SCR-007
 * User Story: US007
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, FormControl, InputLabel, Select, MenuItem, TextField, FormControlLabel, Checkbox, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface AssociarContaExternaProps {
  // Props can be added as needed
}

export const AssociarContaExterna: React.FC<AssociarContaExternaProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-007.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-007.text.info_titulo')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-007.text.info_descricao')}
</Typography>

        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-007.select.banco.label')}</InputLabel>
  <Select label={t('SCR-007.select.banco.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <TextField
  label={t('SCR-007.textfield.iban.label')}
  placeholder={t('SCR-007.textfield.iban.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-007.textfield.iban.helper')}
/>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-007.checkbox.termos')}
/>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="outlined" fullWidth>
          {t('SCR-007.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-007.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default AssociarContaExterna;
