/**
 * Categorias Elegíveis
 * Screen ID: SCR-002
 * User Story: US002
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  Card,
  CardContent,
  Button,
  AppBar,
  Toolbar,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface CategoriasElegveisProps {
  // Props can be added as needed
}

export const CategoriasElegveis: React.FC<CategoriasElegveisProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-002.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-002.text.intro_text')}
</Typography>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-002.card.categoria_supermercados')}</Typography>
  </CardContent>
</Card>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-002.card.categoria_combustivel')}</Typography>
  </CardContent>
</Card>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-002.card.categoria_restauracao')}</Typography>
  </CardContent>
</Card>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-002.card.categoria_farmacia')}</Typography>
  </CardContent>
</Card>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-002.card.categoria_outros')}</Typography>
  </CardContent>
</Card>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-002.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default CategoriasElegveis;
