/**
 * Confirmação de Transferência
 * Screen ID: SCR-005
 * User Story: US005
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, TextField, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ConfirmaodeTransfernciaProps {
  // Props can be added as needed
}

export const ConfirmaodeTransferncia: React.FC<ConfirmaodeTransfernciaProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-005.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-005.text.resumo_titulo')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-005.text.beneficiario')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-005.text.iban')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-005.text.valor')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-005.text.descricao')}
</Typography>

        <TextField
  label={t('SCR-005.textfield.codigo_validacao.label')}
  placeholder={t('SCR-005.textfield.codigo_validacao.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-005.textfield.codigo_validacao.helper')}
/>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="outlined" fullWidth>
          {t('SCR-005.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-005.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ConfirmaodeTransferncia;
