/**
 * Confirmação de Resgate
 * Screen ID: SCR-007
 * User Story: US007
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  Alert,
  Card,
  CardContent,
  Button,
  AppBar,
  Toolbar,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ConfirmaodeResgateProps {
  // Props can be added as needed
}

export const ConfirmaodeResgate: React.FC<ConfirmaodeResgateProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-007.header.title')}
          </Typography>
          <IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Alert severity="info" sx={{ mb: 2 }}>
  {t('SCR-007.alert.sucesso_alert')}
</Alert>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-007.text.mensagem_confirmacao')}
</Typography>

        <Typography variant="h5" gutterBottom>
  {t('SCR-007.title.detalhes_title')}
</Typography>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-007.card.detalhes_resgate')}</Typography>
  </CardContent>
</Card>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-007.button.ver_historico_btn')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-007.button.voltar_inicio_btn')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-007.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ConfirmaodeResgate;
