/**
 * Consulta de Saldos
 * Screen ID: SCR-001
 * User Story: US001
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, Grid, Card, CardContent, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ConsultadeSaldosProps {
  // Props can be added as needed
}

export const ConsultadeSaldos: React.FC<ConsultadeSaldosProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-001.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Grid container spacing={2}>
    <Grid item xs={6}>
      <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-001.card.saldo_disponivel.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-001.card.saldo_disponivel.value')}</Typography>
  </CardContent>
</Card>
    </Grid>
    <Grid item xs={6}>
      <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-001.card.saldo_contabilistico.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-001.card.saldo_contabilistico.value')}</Typography>
  </CardContent>
</Card>
    </Grid>
  </Grid>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-001.card.plafond_disponivel.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-001.card.plafond_disponivel.value')}</Typography>
  </CardContent>
</Card>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-001.button.ver_movimentos')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-001.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ConsultadeSaldos;
