/**
 * Detalhes do Programa
 * Screen ID: SCR-003
 * User Story: US003
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  List,
  ListItem,
  ListItemText,
  FormControlLabel,
  Checkbox,
  Button,
  AppBar,
  Toolbar,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface DetalhesdoProgramaProps {
  // Props can be added as needed
}

export const DetalhesdoPrograma: React.FC<DetalhesdoProgramaProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-003.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-003.title.termos_title')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-003.text.termos_text')}
</Typography>

        <Typography variant="h5" gutterBottom>
  {t('SCR-003.title.como_funciona_title')}
</Typography>

        <List>
  <ListItem>
    <ListItemText primary={t('SCR-003.list.como_funciona_list.item1')} />
  </ListItem>
</List>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-003.checkbox.aceito_termos')}
/>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-003.button.confirmar_adesao_btn')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-003.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default DetalhesdoPrograma;
