/**
 * Filtros de Movimentos
 * Screen ID: SCR-004
 * User Story: US003
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, FormControl, InputLabel, Select, MenuItem, TextField, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface FiltrosdeMovimentosProps {
  // Props can be added as needed
}

export const FiltrosdeMovimentos: React.FC<FiltrosdeMovimentosProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-004.header.title')}
          </Typography>
          <IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-004.select.tipo_movimento.label')}</InputLabel>
  <Select label={t('SCR-004.select.tipo_movimento.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <TextField
  label={t('SCR-004.textfield.periodo_input.label')}
  placeholder={t('SCR-004.textfield.periodo_input.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.periodo_input.helper')}
/>

        <TextField
  label={t('SCR-004.textfield.valor_min.label')}
  placeholder={t('SCR-004.textfield.valor_min.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.valor_min.helper')}
/>

        <TextField
  label={t('SCR-004.textfield.valor_max.label')}
  placeholder={t('SCR-004.textfield.valor_max.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.valor_max.helper')}
/>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="outlined" fullWidth onClick={() => navigate(-1)}>
          {t('SCR-004.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-004.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default FiltrosdeMovimentos;
