/**
 * Gestão de Consentimentos
 * Screen ID: SCR-009
 * User Story: US009
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, FormControlLabel, Checkbox, Alert, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface GestodeConsentimentosProps {
  // Props can be added as needed
}

export const GestodeConsentimentos: React.FC<GestodeConsentimentosProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-009.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-009.text.info_rgpd')}
</Typography>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-009.checkbox.partilha_dados_marketing')}
/>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-009.checkbox.notificacoes_email')}
/>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-009.checkbox.notificacoes_sms')}
/>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-009.checkbox.open_banking')}
/>

        <Alert severity="info" sx={{ mb: 2 }}>
  {t('SCR-009.alert.info_psd2')}
</Alert>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="outlined" fullWidth>
          {t('SCR-009.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-009.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default GestodeConsentimentos;
