/**
 * Lista de Movimentos
 * Screen ID: SCR-002
 * User Story: US002
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, TextField, Button, Card, CardContent, Divider, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ListadeMovimentosProps {
  // Props can be added as needed
}

export const ListadeMovimentos: React.FC<ListadeMovimentosProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-002.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <TextField
  label={t('SCR-002.textfield.search_field.label')}
  placeholder={t('SCR-002.textfield.search_field.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-002.textfield.search_field.helper')}
/>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-002.button.filtros_button')}
</Button>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-002.card.movimento_item_1.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-002.card.movimento_item_1.value')}</Typography>
  </CardContent>
</Card>

        <Divider sx={{ my: 2 }} />

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-002.card.movimento_item_2.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-002.card.movimento_item_2.value')}</Typography>
  </CardContent>
</Card>

        <Divider sx={{ my: 2 }} />

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-002.card.movimento_item_3.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-002.card.movimento_item_3.value')}</Typography>
  </CardContent>
</Card>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-002.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ListadeMovimentos;
