/**
 * Nova Transferência
 * Screen ID: SCR-004
 * User Story: US004
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, TextField, FormControl, InputLabel, Select, MenuItem, Alert, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface NovaTransfernciaProps {
  // Props can be added as needed
}

export const NovaTransferncia: React.FC<NovaTransfernciaProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-004.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <TextField
  label={t('SCR-004.textfield.iban_destino.label')}
  placeholder={t('SCR-004.textfield.iban_destino.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.iban_destino.helper')}
/>

        <TextField
  label={t('SCR-004.textfield.nome_beneficiario.label')}
  placeholder={t('SCR-004.textfield.nome_beneficiario.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.nome_beneficiario.helper')}
/>

        <TextField
  label={t('SCR-004.textfield.valor.label')}
  placeholder={t('SCR-004.textfield.valor.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.valor.helper')}
/>

        <TextField
  label={t('SCR-004.textfield.descricao.label')}
  placeholder={t('SCR-004.textfield.descricao.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.descricao.helper')}
/>

        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-004.select.conta_origem.label')}</InputLabel>
  <Select label={t('SCR-004.select.conta_origem.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <Alert severity="info" sx={{ mb: 2 }}>
  {t('SCR-004.alert.info_comissoes')}
</Alert>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="outlined" fullWidth>
          {t('SCR-004.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-004.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default NovaTransferncia;
