/**
 * Programa Cashback
 * Screen ID: SCR-001
 * User Story: US001
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  Card,
  CardContent,
  List,
  ListItem,
  ListItemText,
  Button,
  AppBar,
  Toolbar,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ProgramaCashbackProps {
  // Props can be added as needed
}

export const ProgramaCashback: React.FC<ProgramaCashbackProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-001.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-001.title.hero_title')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-001.text.hero_description')}
</Typography>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-001.card.saldo_disponivel')}</Typography>
  </CardContent>
</Card>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-001.card.cashback_mes')}</Typography>
  </CardContent>
</Card>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-001.card.cashback_total')}</Typography>
  </CardContent>
</Card>

        <Typography variant="h5" gutterBottom>
  {t('SCR-001.title.beneficios_title')}
</Typography>

        <List>
  <ListItem>
    <ListItemText primary={t('SCR-001.list.beneficios_list.item1')} />
  </ListItem>
</List>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-001.button.aderir_btn')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-001.button.ver_categorias_btn')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="outlined" fullWidth>
          {t('SCR-001.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-001.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ProgramaCashback;
