/**
 * Resgatar Cashback
 * Screen ID: SCR-006
 * User Story: US006
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  Card,
  CardContent,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Button,
  AppBar,
  Toolbar,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ResgatarCashbackProps {
  // Props can be added as needed
}

export const ResgatarCashback: React.FC<ResgatarCashbackProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-006.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-006.card.saldo_resgatavel')}</Typography>
  </CardContent>
</Card>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.minimo_resgate')}
</Typography>

        <TextField
  label={t('SCR-006.textfield.valor_resgate.label')}
  placeholder={t('SCR-006.textfield.valor_resgate.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-006.textfield.valor_resgate.helper')}
/>

        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-006.select.metodo_resgate.label')}</InputLabel>
  <Select label={t('SCR-006.select.metodo_resgate.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <TextField
  label={t('SCR-006.textfield.conta_destino.label')}
  placeholder={t('SCR-006.textfield.conta_destino.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-006.textfield.conta_destino.helper')}
/>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-006.button.confirmar_resgate_btn')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="outlined" fullWidth>
          {t('SCR-006.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-006.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ResgatarCashback;
