/**
 * Sucesso da Transferência
 * Screen ID: SCR-006
 * User Story: US006
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface SucessodaTransfernciaProps {
  // Props can be added as needed
}

export const SucessodaTransferncia: React.FC<SucessodaTransfernciaProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-006.header.title')}
          </Typography>
          <IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.mensagem_sucesso')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.referencia')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.data_processamento')}
</Typography>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-006.button.ver_comprovativo')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-006.button.nova_transferencia')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-006.button.voltar_inicio')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-006.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default SucessodaTransferncia;
