/**
 * Condições de Financiamento
 * Screen ID: SCR-003
 * User Story: US002
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, TextField, FormControl, InputLabel, Select, MenuItem, Alert, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface CondiesdeFinanciamentoProps {
  // Props can be added as needed
}

export const CondiesdeFinanciamento: React.FC<CondiesdeFinanciamentoProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-003.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-003.title.step_title')}
</Typography>

        <TextField
  label={t('SCR-003.textfield.prazo_anos.label')}
  placeholder={t('SCR-003.textfield.prazo_anos.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-003.textfield.prazo_anos.helper')}
/>

        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-003.select.tipo_taxa.label')}</InputLabel>
  <Select label={t('SCR-003.select.tipo_taxa.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <TextField
  label={t('SCR-003.textfield.taxa_juro.label')}
  placeholder={t('SCR-003.textfield.taxa_juro.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-003.textfield.taxa_juro.helper')}
/>

        <Alert severity="info" sx={{ mb: 2 }}>
  {t('SCR-003.alert.info_taxa')}
</Alert>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-003.button.btn_continuar')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-003.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default CondiesdeFinanciamento;
