/**
 * Dados do Imóvel
 * Screen ID: SCR-002
 * User Story: US002
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, TextField, FormControl, InputLabel, Select, MenuItem, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface DadosdoImvelProps {
  // Props can be added as needed
}

export const DadosdoImvel: React.FC<DadosdoImvelProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-002.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-002.title.step_title')}
</Typography>

        <TextField
  label={t('SCR-002.textfield.valor_imovel.label')}
  placeholder={t('SCR-002.textfield.valor_imovel.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-002.textfield.valor_imovel.helper')}
/>

        <TextField
  label={t('SCR-002.textfield.valor_entrada.label')}
  placeholder={t('SCR-002.textfield.valor_entrada.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-002.textfield.valor_entrada.helper')}
/>

        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-002.select.tipo_imovel.label')}</InputLabel>
  <Select label={t('SCR-002.select.tipo_imovel.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-002.select.finalidade.label')}</InputLabel>
  <Select label={t('SCR-002.select.finalidade.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-002.button.btn_continuar')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-002.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default DadosdoImvel;
