/**
 * Dados Pessoais
 * Screen ID: SCR-004
 * User Story: US003
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, TextField, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface DadosPessoaisProps {
  // Props can be added as needed
}

export const DadosPessoais: React.FC<DadosPessoaisProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-004.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-004.title.step_title')}
</Typography>

        <TextField
  label={t('SCR-004.textfield.nome_completo.label')}
  placeholder={t('SCR-004.textfield.nome_completo.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.nome_completo.helper')}
/>

        <TextField
  label={t('SCR-004.textfield.email.label')}
  placeholder={t('SCR-004.textfield.email.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.email.helper')}
/>

        <TextField
  label={t('SCR-004.textfield.telefone.label')}
  placeholder={t('SCR-004.textfield.telefone.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.telefone.helper')}
/>

        <TextField
  label={t('SCR-004.textfield.nif.label')}
  placeholder={t('SCR-004.textfield.nif.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.nif.helper')}
/>

        <TextField
  label={t('SCR-004.textfield.data_nascimento.label')}
  placeholder={t('SCR-004.textfield.data_nascimento.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-004.textfield.data_nascimento.helper')}
/>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-004.button.btn_continuar')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-004.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default DadosPessoais;
