/**
 * Resultado da Simulação
 * Screen ID: SCR-006
 * User Story: US004
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, Grid, Card, CardContent, Divider, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ResultadodaSimulaoProps {
  // Props can be added as needed
}

export const ResultadodaSimulao: React.FC<ResultadodaSimulaoProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-006.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-006.title.resultado_title')}
</Typography>

        <Grid container spacing={2}>
    <Grid item xs={6}>
      <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-006.card.prestacao_mensal.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-006.card.prestacao_mensal.value')}</Typography>
  </CardContent>
</Card>
    </Grid>
    <Grid item xs={6}>
      <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-006.card.montante_total.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-006.card.montante_total.value')}</Typography>
  </CardContent>
</Card>
    </Grid>
    <Grid item xs={6}>
      <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-006.card.taeg.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-006.card.taeg.value')}</Typography>
  </CardContent>
</Card>
    </Grid>
    <Grid item xs={6}>
      <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-006.card.tan.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-006.card.tan.value')}</Typography>
  </CardContent>
</Card>
    </Grid>
  </Grid>

        <Divider sx={{ my: 2 }} />

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.detalhes_title')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.montante_financiado')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.prazo_total')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.primeira_prestacao')}
</Typography>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-006.button.btn_submeter_pedido')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-006.button.btn_nova_simulacao')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="outlined" fullWidth onClick={() => navigate(-1)}>
          {t('SCR-006.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-006.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ResultadodaSimulao;
