/**
 * Situação Profissional
 * Screen ID: SCR-005
 * User Story: US003
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, FormControl, InputLabel, Select, MenuItem, TextField, FormControlLabel, Checkbox, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface SituaoProfissionalProps {
  // Props can be added as needed
}

export const SituaoProfissional: React.FC<SituaoProfissionalProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-005.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-005.title.step_title')}
</Typography>

        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-005.select.situacao_profissional.label')}</InputLabel>
  <Select label={t('SCR-005.select.situacao_profissional.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <TextField
  label={t('SCR-005.textfield.rendimento_mensal.label')}
  placeholder={t('SCR-005.textfield.rendimento_mensal.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-005.textfield.rendimento_mensal.helper')}
/>

        <TextField
  label={t('SCR-005.textfield.despesas_mensais.label')}
  placeholder={t('SCR-005.textfield.despesas_mensais.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-005.textfield.despesas_mensais.helper')}
/>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-005.checkbox.aceito_termos')}
/>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-005.button.btn_simular')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-005.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default SituaoProfissional;
