/**
 * Prototype Module - Main Entry Point
 * Generates React prototypes from wireframes and user stories
 */

export * from './storage.js';
export * from './compare.js';

import {
  PrototypeRecord,
  GeneratedScreen,
  Journey,
  ScreenComponent,
  createPrototype,
  updatePrototype,
  loadPrototype,
  listPrototypes,
  prototypeExists,
  getLatestVersion,
} from './storage.js';
import { comparePrototypes, generateComparisonSummary, PrototypeComparison } from './compare.js';

// ============================================
// TYPES
// ============================================

export interface WireframeElement {
  type: string;
  name: string;
  props?: Record<string, unknown>;
  children?: WireframeElement[];
  i18nKey?: string;
  valuePT?: string;
  valueEN?: string;
}

export interface WireframeScreen {
  screenId: string;
  screenName: string;
  userStory?: string;
  header?: {
    title: string;
    titlePT?: string;
    titleEN?: string;
    backButton?: boolean;
    closeButton?: boolean;
  };
  body: {
    sections: Array<{
      type: string;
      components: WireframeElement[];
    }>;
  };
  footer?: {
    primaryAction?: string;
    primaryActionPT?: string;
    primaryActionEN?: string;
    secondaryAction?: string;
    secondaryActionPT?: string;
    secondaryActionEN?: string;
  };
}

export interface PrototypeInput {
  bdevCode: string;
  journeys: Journey[];
  wireframes: WireframeScreen[];
  approvedBy?: 'FA' | 'Client';
}

// ============================================
// CODE GENERATION
// ============================================

/**
 * Generates React component code for a screen
 */
function generateScreenCode(screen: WireframeScreen): string {
  const componentName = screen.screenName
    .replace(/[^a-zA-Z0-9]/g, '')
    .replace(/^./, c => c.toUpperCase());

  const imports = new Set<string>(['Box', 'Typography']);
  const bodyComponents: string[] = [];

  // Process body sections
  for (const section of screen.body.sections) {
    for (const component of section.components) {
      const { code, importList } = generateComponentCode(component, screen.screenId);
      bodyComponents.push(code);
      importList.forEach(i => imports.add(i));
    }
  }

  // Generate footer actions
  let footerCode = '';
  if (screen.footer?.primaryAction || screen.footer?.secondaryAction) {
    imports.add('Button');
    const buttons: string[] = [];
    if (screen.footer.secondaryAction) {
      buttons.push(`        <Button variant="outlined" fullWidth>
          {t('${screen.screenId}.footer.secondary')}
        </Button>`);
    }
    if (screen.footer.primaryAction) {
      buttons.push(`        <Button variant="contained" color="primary" fullWidth>
          {t('${screen.screenId}.footer.primary')}
        </Button>`);
    }
    footerCode = `
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
${buttons.join('\n')}
      </Box>`;
  }

  // Generate header
  let headerCode = '';
  if (screen.header) {
    imports.add('AppBar');
    imports.add('Toolbar');
    imports.add('IconButton');
    const backButton = screen.header.backButton
      ? `<IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>`
      : '';
    const closeButton = screen.header.closeButton
      ? `<IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>`
      : '';
    headerCode = `
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          ${backButton}
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('${screen.screenId}.header.title')}
          </Typography>
          ${closeButton}
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}`;
  }

  const code = `/**
 * ${screen.screenName}
 * Screen ID: ${screen.screenId}
 * ${screen.userStory ? `User Story: ${screen.userStory}` : ''}
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  ${Array.from(imports).join(',\n  ')},
} from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@bctt/design-system/icons';

export interface ${componentName}Props {
  // Props can be added as needed
}

export const ${componentName}: React.FC<${componentName}Props> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      ${headerCode}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
${bodyComponents.map(c => '        ' + c).join('\n\n')}
      </Box>
      ${footerCode}
    </Box>
  );
};

export default ${componentName};
`;

  return code;
}

/**
 * Generates code for a single component
 */
function generateComponentCode(
  element: WireframeElement,
  screenId: string,
  indent: number = 0
): { code: string; importList: string[] } {
  const imports: string[] = [];
  let code = '';
  const i18nKey = element.i18nKey || `${screenId}.${element.type}.${element.name}`;

  switch (element.type.toLowerCase()) {
    case 'button':
      imports.push('Button');
      code = `<Button
  variant="${element.props?.variant || 'contained'}"
  color="${element.props?.color || 'primary'}"
  fullWidth
>
  {t('${i18nKey}')}
</Button>`;
      break;

    case 'textfield':
    case 'input':
      imports.push('TextField');
      code = `<TextField
  label={t('${i18nKey}.label')}
  placeholder={t('${i18nKey}.placeholder')}
  fullWidth
  ${element.props?.required ? 'required' : ''}
  ${element.props?.type ? `type="${element.props.type}"` : ''}
  helperText={t('${i18nKey}.helper')}
/>`;
      break;

    case 'card':
      imports.push('Card', 'CardContent');
      const cardChildren = element.children
        ? element.children.map(c => {
            const result = generateComponentCode(c, screenId, indent + 2);
            result.importList.forEach(i => imports.push(i));
            return result.code;
          }).join('\n')
        : `<Typography>{t('${i18nKey}')}</Typography>`;
      code = `<Card sx={{ mb: 2 }}>
  <CardContent>
    ${cardChildren}
  </CardContent>
</Card>`;
      break;

    case 'title':
    case 'heading':
      imports.push('Typography');
      code = `<Typography variant="${element.props?.variant || 'h5'}" gutterBottom>
  {t('${i18nKey}')}
</Typography>`;
      break;

    case 'text':
    case 'description':
    case 'paragraph':
      imports.push('Typography');
      code = `<Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('${i18nKey}')}
</Typography>`;
      break;

    case 'alert':
      imports.push('Alert');
      code = `<Alert severity="${element.props?.severity || 'info'}" sx={{ mb: 2 }}>
  {t('${i18nKey}')}
</Alert>`;
      break;

    case 'divider':
      imports.push('Divider');
      code = `<Divider sx={{ my: 2 }} />`;
      break;

    case 'select':
      imports.push('FormControl', 'InputLabel', 'Select', 'MenuItem');
      code = `<FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('${i18nKey}.label')}</InputLabel>
  <Select label={t('${i18nKey}.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>`;
      break;

    case 'checkbox':
      imports.push('FormControlLabel', 'Checkbox');
      code = `<FormControlLabel
  control={<Checkbox />}
  label={t('${i18nKey}')}
/>`;
      break;

    case 'radio':
      imports.push('FormControl', 'FormLabel', 'RadioGroup', 'FormControlLabel', 'Radio');
      code = `<FormControl component="fieldset" sx={{ mb: 2 }}>
  <FormLabel>{t('${i18nKey}.label')}</FormLabel>
  <RadioGroup>
    <FormControlLabel value="option1" control={<Radio />} label={t('${i18nKey}.option1')} />
    <FormControlLabel value="option2" control={<Radio />} label={t('${i18nKey}.option2')} />
  </RadioGroup>
</FormControl>`;
      break;

    case 'list':
      imports.push('List', 'ListItem', 'ListItemText');
      code = `<List>
  <ListItem>
    <ListItemText primary={t('${i18nKey}.item1')} />
  </ListItem>
</List>`;
      break;

    default:
      imports.push('Box');
      code = `<Box sx={{ mb: 2 }}>
  {/* ${element.type}: ${element.name} */}
  <Typography>{t('${i18nKey}')}</Typography>
</Box>`;
  }

  return { code, importList: imports };
}

/**
 * Generates App.tsx with routes for all screens
 */
function generateAppRouter(screens: GeneratedScreen[], bdevCode: string): string {
  const imports = screens.map(s => {
    const componentName = s.screenName.replace(/[^a-zA-Z0-9]/g, '').replace(/^./, c => c.toUpperCase());
    return `import { ${componentName} } from './screens/${componentName}';`;
  }).join('\n');

  const routes = screens.map(s => {
    const componentName = s.screenName.replace(/[^a-zA-Z0-9]/g, '').replace(/^./, c => c.toUpperCase());
    const path = s.screenId.toLowerCase().replace(/[^a-z0-9]/g, '-');
    return `        <Route path="/${path}" element={<${componentName} />} />`;
  }).join('\n');

  return `/**
 * App Router
 * BDEV: ${bdevCode}
 *
 * PROTOTYPE - Non-functional application
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { bcttTheme } from '@bctt/design-system';
import './i18n'; // i18n configuration

${imports}

const App: React.FC = () => {
  return (
    <ThemeProvider theme={bcttTheme}>
      <CssBaseline />
      <BrowserRouter>
        <Routes>
${routes}
          <Route path="*" element={<Navigate to="/${screens[0]?.screenId.toLowerCase().replace(/[^a-z0-9]/g, '-') || ''}" replace />} />
        </Routes>
      </BrowserRouter>
    </ThemeProvider>
  );
};

export default App;
`;
}

/**
 * Extracts translations from wireframe
 */
function extractTranslations(wireframe: WireframeScreen): { pt: Record<string, string>; en: Record<string, string> } {
  const pt: Record<string, string> = {};
  const en: Record<string, string> = {};

  // Header translations
  if (wireframe.header) {
    pt[`${wireframe.screenId}.header.title`] = wireframe.header.titlePT || wireframe.header.title;
    en[`${wireframe.screenId}.header.title`] = wireframe.header.titleEN || wireframe.header.title;
  }

  // Footer translations
  if (wireframe.footer) {
    if (wireframe.footer.primaryAction) {
      pt[`${wireframe.screenId}.footer.primary`] = wireframe.footer.primaryActionPT || wireframe.footer.primaryAction;
      en[`${wireframe.screenId}.footer.primary`] = wireframe.footer.primaryActionEN || wireframe.footer.primaryAction;
    }
    if (wireframe.footer.secondaryAction) {
      pt[`${wireframe.screenId}.footer.secondary`] = wireframe.footer.secondaryActionPT || wireframe.footer.secondaryAction;
      en[`${wireframe.screenId}.footer.secondary`] = wireframe.footer.secondaryActionEN || wireframe.footer.secondaryAction;
    }
  }

  // Body component translations
  function processElements(elements: WireframeElement[], prefix: string) {
    for (const element of elements) {
      const key = element.i18nKey || `${prefix}.${element.type}.${element.name}`;
      if (element.valuePT) pt[key] = element.valuePT;
      if (element.valueEN) en[key] = element.valueEN;

      // Process children recursively
      if (element.children) {
        processElements(element.children, key);
      }
    }
  }

  for (const section of wireframe.body.sections) {
    processElements(section.components, wireframe.screenId);
  }

  return { pt, en };
}

// ============================================
// MAIN FUNCTIONS
// ============================================

/**
 * Creates a new prototype from wireframes
 */
export function generatePrototype(input: PrototypeInput): PrototypeRecord {
  const screens: GeneratedScreen[] = input.wireframes.map(wireframe => {
    const translations = extractTranslations(wireframe);
    const code = generateScreenCode(wireframe);
    const components: ScreenComponent[] = wireframe.body.sections.flatMap(s =>
      s.components.map(c => ({
        type: c.type,
        props: c.props || {},
        i18nKey: c.i18nKey,
        children: c.children as ScreenComponent[] | undefined,
      }))
    );

    return {
      screenId: wireframe.screenId,
      screenName: wireframe.screenName,
      userStory: wireframe.userStory,
      components,
      code,
      translations,
    };
  });

  // Check if prototype exists
  if (prototypeExists(input.bdevCode)) {
    const existingPrototype = loadPrototype(input.bdevCode);
    if (existingPrototype) {
      // Create new version with changes
      return updatePrototype(
        input.bdevCode,
        screens,
        input.journeys,
        input.approvedBy || 'PA',
        `Updated prototype based on ${input.approvedBy || 'PA'} input`
      );
    }
  }

  // Create new prototype
  return createPrototype(input.bdevCode, input.journeys, screens, input.approvedBy);
}

/**
 * Gets or creates a prototype for a BDEV
 */
export function getOrCreatePrototype(input: PrototypeInput): PrototypeRecord {
  const existing = loadPrototype(input.bdevCode);

  if (existing) {
    return existing;
  }

  return generatePrototype(input);
}

/**
 * Compares FA approved version with Client approved version
 */
export function compareFAvsClient(bdevCode: string): PrototypeComparison | null {
  const prototypes = listPrototypes(bdevCode);

  const faApproved = prototypes.find(p => p.status === 'fa_approved');
  const clientApproved = prototypes.find(p => p.status === 'client_approved');

  if (!faApproved || !clientApproved) {
    return null;
  }

  const faPrototype = loadPrototype(bdevCode, faApproved.version);
  const clientPrototype = loadPrototype(bdevCode, clientApproved.version);

  if (!faPrototype || !clientPrototype) {
    return null;
  }

  return comparePrototypes(faPrototype, clientPrototype);
}

/**
 * Applies client changes to create final version
 */
export function applyClientChanges(bdevCode: string): PrototypeRecord | null {
  const comparison = compareFAvsClient(bdevCode);

  if (!comparison) {
    return null;
  }

  const clientPrototype = loadPrototype(bdevCode);
  if (!clientPrototype || clientPrototype.status !== 'client_approved') {
    return null;
  }

  // Create final version based on client approved
  const finalPrototype = updatePrototype(
    bdevCode,
    clientPrototype.screens,
    clientPrototype.journeySnapshot,
    'PA',
    `Final version created based on client approved changes`
  );

  // Generate App router code
  finalPrototype.appCode = generateAppRouter(finalPrototype.screens, bdevCode);

  // Merge all translations
  const allTranslations = { pt: {} as Record<string, string>, en: {} as Record<string, string> };
  for (const screen of finalPrototype.screens) {
    Object.assign(allTranslations.pt, screen.translations.pt);
    Object.assign(allTranslations.en, screen.translations.en);
  }
  finalPrototype.translationsJson = allTranslations;

  return finalPrototype;
}

/**
 * Exports prototype as a structured package
 */
export function exportPrototype(bdevCode: string, version?: number): {
  screens: Array<{ filename: string; code: string }>;
  app: { filename: string; code: string };
  translations: {
    pt: { filename: string; content: string };
    en: { filename: string; content: string };
  };
  readme: string;
} | null {
  const prototype = loadPrototype(bdevCode, version);
  if (!prototype) return null;

  const screens = prototype.screens.map(s => ({
    filename: `${s.screenName.replace(/[^a-zA-Z0-9]/g, '')}.tsx`,
    code: s.code,
  }));

  const appCode = prototype.appCode || generateAppRouter(prototype.screens, bdevCode);

  const allPt: Record<string, string> = {};
  const allEn: Record<string, string> = {};
  for (const screen of prototype.screens) {
    Object.assign(allPt, screen.translations.pt);
    Object.assign(allEn, screen.translations.en);
  }

  const readme = `# ${bdevCode} - Prototype

## Generated by PA (Prototype Agent)

### Version: ${prototype.version}
### Status: ${prototype.status}

## Screens
${prototype.screens.map(s => `- ${s.screenName} (${s.screenId})`).join('\n')}

## Setup
1. Copy files to your React project
2. Install dependencies: \`npm install @bctt/design-system react-router-dom react-i18next i18next\`
3. Import the App component

## Notes
- This is a non-functional prototype using BCTT Design System
- All actions are placeholders
- Translations are included in PT and EN
- Uses bctt-design-system components (Button, Input, Card, etc.)
`;

  return {
    screens,
    app: { filename: 'App.tsx', code: appCode },
    translations: {
      pt: { filename: 'pt.json', content: JSON.stringify(allPt, null, 2) },
      en: { filename: 'en.json', content: JSON.stringify(allEn, null, 2) },
    },
    readme,
  };
}
