/**
 * App Router
 * BDEV: BDEV00000010
 *
 * PROTOTYPE - Non-functional application
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { bcttTheme } from '@bctt/design-system';

import { AutenticaoSCA } from './screens/AutenticaoSCA';
import { ConsultadeSaldoseMovimentos } from './screens/ConsultadeSaldoseMovimentos';
import { DetalhesdoMovimento } from './screens/DetalhesdoMovimento';
import { FiltrosdeMovimentos } from './screens/FiltrosdeMovimentos';
import { RenovarConsentimentoPSD2 } from './screens/RenovarConsentimentoPSD2';
import { ExportarExtrato } from './screens/ExportarExtrato';

const App: React.FC = () => {
  return (
    <ThemeProvider theme={bcttTheme}>
      <CssBaseline />
      <BrowserRouter>
        <Routes>
        <Route path="/scr-001" element={<AutenticaoSCA />} />
        <Route path="/scr-002" element={<ConsultadeSaldoseMovimentos />} />
        <Route path="/scr-003" element={<DetalhesdoMovimento />} />
        <Route path="/scr-004" element={<FiltrosdeMovimentos />} />
        <Route path="/scr-005" element={<RenovarConsentimentoPSD2 />} />
        <Route path="/scr-006" element={<ExportarExtrato />} />
          <Route path="*" element={<Navigate to="/scr-001" replace />} />
        </Routes>
      </BrowserRouter>
    </ThemeProvider>
  );
};

export default App;
