/**
 * App Router
 * BDEV: BDEV00000009
 *
 * PROTOTYPE - Non-functional application
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { bcttTheme } from '@bctt/design-system';

import { ConsultadeSaldos } from './screens/ConsultadeSaldos';
import { ListadeMovimentos } from './screens/ListadeMovimentos';
import { DetalhedoMovimento } from './screens/DetalhedoMovimento';
import { FiltrosdeMovimentos } from './screens/FiltrosdeMovimentos';
import { ResultadosFiltrados } from './screens/ResultadosFiltrados';
import { EstadodeErro } from './screens/EstadodeErro';

const App: React.FC = () => {
  return (
    <ThemeProvider theme={bcttTheme}>
      <CssBaseline />
      <BrowserRouter>
        <Routes>
        <Route path="/scr-001" element={<ConsultadeSaldos />} />
        <Route path="/scr-002" element={<ListadeMovimentos />} />
        <Route path="/scr-003" element={<DetalhedoMovimento />} />
        <Route path="/scr-004" element={<FiltrosdeMovimentos />} />
        <Route path="/scr-005" element={<ResultadosFiltrados />} />
        <Route path="/scr-006" element={<EstadodeErro />} />
          <Route path="*" element={<Navigate to="/scr-001" replace />} />
        </Routes>
      </BrowserRouter>
    </ThemeProvider>
  );
};

export default App;
