/**
 * Autenticação SCA
 * Screen ID: SCR-001
 * User Story: US007
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, TextField, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface AutenticaoSCAProps {
  // Props can be added as needed
}

export const AutenticaoSCA: React.FC<AutenticaoSCAProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-001.header.title')}
          </Typography>
          <IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-001.title.auth_title')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-001.text.auth_description')}
</Typography>

        <TextField
  label={t('SCR-001.textfield.sca_code.label')}
  placeholder={t('SCR-001.textfield.sca_code.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-001.textfield.sca_code.helper')}
/>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-001.text.sca_helper')}
</Typography>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-001.button.confirm_auth')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-001.button.resend_code')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="outlined" fullWidth onClick={() => navigate(-1)}>
          {t('SCR-001.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-001.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default AutenticaoSCA;
