/**
 * Estado de Erro
 * Screen ID: SCR-ERROR
 * User Story: US001-US006
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  Alert,
  Button,
  AppBar,
  Toolbar,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface EstadodeErroProps {
  // Props can be added as needed
}

export const EstadodeErro: React.FC<EstadodeErroProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-ERROR.header.title')}
          </Typography>
          <IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Alert severity="info" sx={{ mb: 2 }}>
  {t('SCR-ERROR.alert.error_message')}
</Alert>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-ERROR.button.retry')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-ERROR.button.contact_support')}
</Button>
      </Box>
      
    </Box>
  );
};

export default EstadodeErro;
