/**
 * Exportação de Extrato
 * Screen ID: SCR-006
 * User Story: US006
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  TextField,
  Button,
  AppBar,
  Toolbar,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ExportaodeExtratoProps {
  // Props can be added as needed
}

export const ExportaodeExtrato: React.FC<ExportaodeExtratoProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-006.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-006.select.export_format.label')}</InputLabel>
  <Select label={t('SCR-006.select.export_format.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-006.select.export_period.label')}</InputLabel>
  <Select label={t('SCR-006.select.export_period.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <TextField
  label={t('SCR-006.textfield.export_email.label')}
  placeholder={t('SCR-006.textfield.export_email.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-006.textfield.export_email.helper')}
/>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.export_info')}
</Typography>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="outlined" fullWidth>
          {t('SCR-006.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-006.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ExportaodeExtrato;
