/**
 * Exportar Extrato
 * Screen ID: SCR-006
 * User Story: US006
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, FormControl, InputLabel, Select, MenuItem, TextField, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ExportarExtratoProps {
  // Props can be added as needed
}

export const ExportarExtrato: React.FC<ExportarExtratoProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-006.header.title')}
          </Typography>
          <IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-006.title.export_title')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.export_description')}
</Typography>

        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-006.select.export_format.label')}</InputLabel>
  <Select label={t('SCR-006.select.export_format.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <TextField
  label={t('SCR-006.textfield.export_date_from.label')}
  placeholder={t('SCR-006.textfield.export_date_from.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-006.textfield.export_date_from.helper')}
/>

        <TextField
  label={t('SCR-006.textfield.export_date_to.label')}
  placeholder={t('SCR-006.textfield.export_date_to.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-006.textfield.export_date_to.helper')}
/>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.export_info')}
</Typography>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-006.button.download_pdf')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-006.button.download_excel')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="outlined" fullWidth onClick={() => navigate(-1)}>
          {t('SCR-006.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-006.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ExportarExtrato;
