/**
 * Lista de Movimentos
 * Screen ID: SCR-005
 * User Story: US004
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  TextField,
  List,
  ListItem,
  ListItemText,
  Button,
  AppBar,
  Toolbar,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ListadeMovimentosProps {
  // Props can be added as needed
}

export const ListadeMovimentos: React.FC<ListadeMovimentosProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-005.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <FormControl fullWidth sx={{ mb: 2 }}>
  <InputLabel>{t('SCR-005.select.filter_period.label')}</InputLabel>
  <Select label={t('SCR-005.select.filter_period.label')}>
    <MenuItem value="">{t('common.select')}</MenuItem>
  </Select>
</FormControl>

        <TextField
  label={t('SCR-005.textfield.filter_start_date.label')}
  placeholder={t('SCR-005.textfield.filter_start_date.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-005.textfield.filter_start_date.helper')}
/>

        <TextField
  label={t('SCR-005.textfield.filter_end_date.label')}
  placeholder={t('SCR-005.textfield.filter_end_date.placeholder')}
  fullWidth
  
  
  helperText={t('SCR-005.textfield.filter_end_date.helper')}
/>

        <List>
  <ListItem>
    <ListItemText primary={t('SCR-005.list.transaction_1.item1')} />
  </ListItem>
</List>

        <List>
  <ListItem>
    <ListItemText primary={t('SCR-005.list.transaction_2.item1')} />
  </ListItem>
</List>

        <List>
  <ListItem>
    <ListItemText primary={t('SCR-005.list.transaction_3.item1')} />
  </ListItem>
</List>

        <Button
  variant="contained"
  color="primary"
  fullWidth
>
  {t('SCR-005.button.load_more')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 1,
      }}>
        <Button variant="contained" color="primary" fullWidth>
          {t('SCR-005.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ListadeMovimentos;
