/**
 * Renovar Consentimento PSD2
 * Screen ID: SCR-005
 * User Story: US008
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, Alert, FormControlLabel, Checkbox, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface RenovarConsentimentoPSD2Props {
  // Props can be added as needed
}

export const RenovarConsentimentoPSD2: React.FC<RenovarConsentimentoPSD2Props> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-005.header.title')}
          </Typography>
          <IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Alert severity="info" sx={{ mb: 2 }}>
  {t('SCR-005.alert.consent_expired')}
</Alert>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-005.text.consent_description')}
</Typography>

        <Typography variant="h5" gutterBottom>
  {t('SCR-005.title.permissions_title')}
</Typography>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-005.checkbox.perm_balance')}
/>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-005.checkbox.perm_transactions')}
/>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-005.text.validity_info')}
</Typography>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-005.button.renew_consent')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-005.button.cancel')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="outlined" fullWidth onClick={() => navigate(-1)}>
          {t('SCR-005.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-005.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default RenovarConsentimentoPSD2;
