/**
 * Seleção de Conta
 * Screen ID: SCR-002
 * User Story: US002
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Typography,
  Card,
  CardContent,
  AppBar,
  Toolbar,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface SeleodeContaProps {
  // Props can be added as needed
}

export const SeleodeConta: React.FC<SeleodeContaProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'greyblue.100', pb: 10 }}>
      
      <AppBar position="fixed" color="default" elevation={0}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-002.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>
      <Toolbar /> {/* Spacer for fixed header */}

      {/* Body Content */}
      <Box sx={{ p: 2, maxWidth: 600, mx: 'auto' }}>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-002.text.select_account_prompt')}
</Typography>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-002.card.account_1')}</Typography>
  </CardContent>
</Card>

        <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography>{t('SCR-002.card.account_2')}</Typography>
  </CardContent>
</Card>
      </Box>
      
    </Box>
  );
};

export default SeleodeConta;
