/**
 * Confirmação Exportação
 * Screen ID: SCR-006
 * User Story: US004
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, Alert, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface ConfirmaoExportaoProps {
  // Props can be added as needed
}

export const ConfirmaoExportao: React.FC<ConfirmaoExportaoProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-006.header.title')}
          </Typography>
          <IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Alert severity="info" sx={{ mb: 2 }}>
  {t('SCR-006.alert.sucesso_exportacao')}
</Alert>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-006.text.info_ficheiro')}
</Typography>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-006.button.abrir_ficheiro')}
</Button>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-006.button.nova_exportacao')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-006.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default ConfirmaoExportao;
