/**
 * Detalhe de Movimento
 * Screen ID: SCR-004
 * User Story: US003
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface DetalhedeMovimentoProps {
  // Props can be added as needed
}

export const DetalhedeMovimento: React.FC<DetalhedeMovimentoProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-004.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-004.text.data')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-004.text.descricao')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-004.text.montante')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-004.text.tipo')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-004.text.saldo_apos')}
</Typography>

        <Button
  variant="contained"
  color="primary"
  fullWidth
  sx={{ mb: 2 }}
 
>
  {t('SCR-004.button.exportar_recibo')}
</Button>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-004.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default DetalhedeMovimento;
