/**
 * Detalhes da Conta
 * Screen ID: SCR-002
 * User Story: US002
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, Grid, Card, CardContent, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface DetalhesdaContaProps {
  // Props can be added as needed
}

export const DetalhesdaConta: React.FC<DetalhesdaContaProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-002.header.title')}
          </Typography>
          
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-002.title.account_title')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-002.text.account_number')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-002.text.account_holder')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-002.text.iban')}
</Typography>

        <Typography variant="body1" color="text.secondary" sx={{ mb: 2 }}>
  {t('SCR-002.text.swift')}
</Typography>

        <Grid container spacing={2}>
    <Grid item xs={6}>
      <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-002.card.saldo_disponivel_detail.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-002.card.saldo_disponivel_detail.value')}</Typography>
  </CardContent>
</Card>
    </Grid>
    <Grid item xs={6}>
      <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-002.card.saldo_contabilistico_detail.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-002.card.saldo_contabilistico_detail.value')}</Typography>
  </CardContent>
</Card>
    </Grid>
    <Grid item xs={6}>
      <Card sx={{ mb: 2 }}>
  <CardContent>
    <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5 }}>{t('SCR-002.card.saldo_autorizado_detail.label')}</Typography>
    <Typography variant="h5" color="text.primary">{t('SCR-002.card.saldo_autorizado_detail.value')}</Typography>
  </CardContent>
</Card>
    </Grid>
  </Grid>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="outlined" fullWidth onClick={() => navigate(-1)}>
          {t('SCR-002.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-002.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default DetalhesdaConta;
