/**
 * Seleção Formato Exportação
 * Screen ID: SCR-005
 * User Story: US004
 *
 * PROTOTYPE - Non-functional component
 * Generated by PA (Prototype Agent)
 */

import React from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { Box, Typography, FormControlLabel, Checkbox, Button, AppBar, Toolbar, IconButton } from '@bctt/design-system';
import { ArrowBack as ArrowBackIcon, Close as CloseIcon } from '@mui/icons-material';

export interface SeleoFormatoExportaoProps {
  // Props can be added as needed
}

export const SeleoFormatoExportao: React.FC<SeleoFormatoExportaoProps> = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();

  return (
    <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', display: 'flex', flexDirection: 'column' }}>
      
      <AppBar position="sticky" color="default" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
        <Toolbar>
          <IconButton edge="start" onClick={() => navigate(-1)}>
            <ArrowBackIcon />
          </IconButton>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            {t('SCR-005.header.title')}
          </Typography>
          <IconButton edge="end" onClick={() => navigate('/')}>
            <CloseIcon />
          </IconButton>
        </Toolbar>
      </AppBar>

      {/* Body Content */}
      <Box sx={{ flex: 1, p: 2 }}>
        <Typography variant="h5" gutterBottom>
  {t('SCR-005.title.titulo_formato')}
</Typography>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-005.checkbox.formato_pdf')}
/>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-005.checkbox.formato_excel')}
/>

        <FormControlLabel
  control={<Checkbox />}
  label={t('SCR-005.checkbox.formato_csv')}
/>
      </Box>
      
      {/* Footer Actions */}
      <Box sx={{
        position: 'sticky',
        bottom: 0,
        p: 2,
        bgcolor: 'background.paper',
        borderTop: 1,
        borderColor: 'divider',
        display: 'flex',
        flexDirection: 'column',
        gap: 2,
        zIndex: 10,
      }}>
        <Button variant="outlined" fullWidth onClick={() => navigate(-1)}>
          {t('SCR-005.footer.secondary')}
        </Button>
        <Button variant="contained" color="primary" fullWidth onClick={() => navigate('/')}>
          {t('SCR-005.footer.primary')}
        </Button>
      </Box>
    </Box>
  );
};

export default SeleoFormatoExportao;
